# Generated By lexicon-dsa CLI tool.
# Author: Saptak Sengupta(deeps.sengupta@gmail.com)
# Github: https://github.com/saptaksengupta/

class Solution:

    # Complete the demoFunction function below.
    # You should change the name accordinglly.
    def isPowerOfFour(self, number):
        if number is 1:
            return True

        if number < 1 or number % 4 is not 0:
            return False
        
        return self.isPowerOfFour(int(number/4))


if __name__ == "__main__":
    instance = Solution()
    res = instance.isPowerOfFour(8)
    print(res)
