# Generated By lexicon-dsa CLI tool.
# Author: Saptak Sengupta(deeps.sengupta@gmail.com)
# Github: https://github.com/saptaksengupta/

# Problem Statement
# Given a “2 x n” board and tiles of size “2 x 1”, 
# count the number of ways to tile the given board using the 2 x 1 tiles. 
# A tile can either be placed horizontally 
# i.e., as a 1 x 2 tile or vertically i.e., as 2 x 1 tile.

class Solution:

    # Complete the demoFunction function below.
    # You should change the name accordinglly.
    def getTilingArrangements(self, n):
        if n == 1:
            return 1
        
        if n == 2:
            return 2
        
        d = {1: 1, 2: 2}

        for i in range(3, n+1):
            d[i] = d[i - 1] + d[i - 2]

        return d[n]

if __name__ == "__main__":
    instance = Solution()
    print(instance.getTilingArrangements(5))
