# Generated By lexicon-dsa CLI tool.
# Author: Saptak Sengupta(deeps.sengupta@gmail.com)
# Github: https://github.com/saptaksengupta/

class Solution:
    
    def generate(self, n):
        for i in range(0, n, 1):
            for j in range(n, n - (i + 1), -1):
                print(j, end="")
            print()
            
if __name__ == "__main__":
    instance = Solution()
    instance.generate(5)
