'use strict';
// Generated By lexicon-dsa CLI tool.
// Author: Saptak Sengupta(deeps.sengupta@gmail.com)
// Github: https://github.com/saptaksengupta/


function getTime(speed, piles) {
    var timeTaken = 0;
    var len = piles.length;
    for(var i = 0; i < len; i++) {
        timeTaken += Math.ceil(piles[i] / speed);
    }
    return timeTaken;
}

var minEatingSpeed = function(piles, hour) {
    var high = Math.max(...piles);
    var low = 1; 
    var bestRes = high;

    while (low < high) {
        var mid = Math.floor((low + high) / 2);

        var time = getTime(mid, piles);

        if (time == hour) {
            return mid;
        }

        if (time < hour) {
            bestRes = mid;
            high = mid - 1;
        } else {
            low = mid + 1;
        }
    }

    return bestRes;
}

console.log(minEatingSpeed([30, 11, 23, 4, 20], 5));

