# Generated By lexicon-dsa CLI tool.
# Author: Saptak Sengupta(deeps.sengupta@gmail.com)
# Github: https://github.com/saptaksengupta/

class Solution:

    # Complete the demoFunction function below.
    # You should change the name accordinglly.

    def climbStairs(self, n: int) -> int:
        d = {1: 1, 2: 2}
        
        for i in range(3, n+1):
            cur = d[i - 1] + d[i - 2]
            d[i] = cur
        
        return d[n]


if __name__ == "__main__":
    instance = Solution()
    res = instance.climbStairs(5)
    print(res)
