# Generated By lexicon-dsa CLI tool.
# Author: Saptak Sengupta(deeps.sengupta@gmail.com)
# Github: https://github.com/saptaksengupta/

import sys

class Solution:
    # Complete the demoFunction function below.
    # You should change the name accordinglly.
    def getMaxSubArraySum(self, nums):
        maxSumSoFar = nums[0]
        maxSumEnding = nums[0]

        for i in range(1, len(nums)):
            maxSumEnding = maxSumEnding + nums[i]

            if maxSumEnding > maxSumSoFar: 
                maxSumSoFar = maxSumEnding
            
            if maxSumEnding < 0:
                maxSumEnding = 0
        
        return maxSumSoFar


if __name__ == "__main__":

    demoArr = [-2,1,-3,4,-1,2,1,-5,4]
    # demoArr = [-2]
    instance = Solution()
    maxSum = instance.getMaxSubArraySum(demoArr)

    print(maxSum)
