# Generated By lexicon-dsa CLI tool.
# Author: Saptak Sengupta(deeps.sengupta@gmail.com)
# Github: https://github.com/saptaksengupta/

class Solution:
    # Complete the demoFunction function below.
    # You should change the name accordinglly.
    def reverseInteger(self, x):
        newInt = 0
        na = x
        x = abs(x)
        while x> 0:
            re = x % 10
            newInt = (newInt * 10) + re
            x = int(x / 10) 
        
        if na < 0:
            newInt = 0 - newInt

        if -(2**31) < newInt < (2**31) - 1:
            return newInt

        return 0


if __name__ == "__main__":
    instance = Solution()
    print(instance.reverseInteger(1534236469))
