# Generated By lexicon-dsa CLI tool.
# Author: Saptak Sengupta(deeps.sengupta@gmail.com)
# Github: https://github.com/saptaksengupta/

class Solution:
    # Complete the demoFunction function below.
    # You should change the name accordinglly.
    def reverseInteger(self, n):
        newInt = 0
        while n > 0:
            re = n % 10
            newInt = (newInt * 10) + re
            n = int(n / 10) 
        return newInt



if __name__ == "__main__":
    instance = Solution()
    print(instance.reverseInteger(123))
