# Generated By lexicon-dsa CLI tool.
# Author: Saptak Sengupta(deeps.sengupta@gmail.com)
# Github: https://github.com/saptaksengupta/

class Solution:

    # Complete the demoFunction function below.
    # You should change the name accordinglly.
    def reverseString(self, str):
        i = 0 
        j = len(str) - 1

        while i < j:
            str[i],str[j] = str[j],str[i]
            i += 1
            j -= 1
        
        return str


if __name__ == "__main__":
    instance = Solution()
    rStr = instance.reverseString(['a', 'b', 'c', 'd', 'e'])
    print(rStr)
