# Generated By lexicon-dsa CLI tool.
# Author: Saptak Sengupta(deeps.sengupta@gmail.com)
# Github: https://github.com/saptaksengupta/

class Solution:

    # Complete the demoFunction function below.
    # You should change the name accordinglly.
    def stringToInteger(self, s):
        resultInt = 0
        isItNegative = False
        valuesToCheck = list(['1', '2', '3', '4', '5', '5' , '6', '7', '8', '9'])

        for i in range(0, len(s)):
            if s[i] != ' ':
                if s[i] == '-':
                    isItNegative = True
                elif s[i] == '+': 
                    isItNegative = True
                elif s[i] in valuesToCheck:
                    resultInt = resultInt * 10 + int(s[i])
                else:
                    break

        
        if resultInt > 4294967296:
            resultInt = 2147483648

        if isItNegative: 
            return -resultInt

        return resultInt


if __name__ == "__main__":
    testString = '   -42'
    instance = Solution()
    print(instance.stringToInteger(testString))
