# Generated By lexicon-dsa CLI tool.
# Author: Saptak Sengupta(deeps.sengupta@gmail.com)
# Github: https://github.com/saptaksengupta/

class Solution:
    # Complete the demoFunction function below.
    # You should change the name accordinglly.
    def validParentheses(self, str):
        pList = []
        oPlist = ['[', '{', '(']
        for i in range(len(str)):
            if str[i] in oPlist:
                pList.append(str[i])
            else:
                popedElem = pList.pop()
                if str[i] == ']' and popedElem != '[':
                    return False

                if str[i] == '}' and popedElem != '{':
                    return False

                if str[i] == ')' and popedElem != '(':
                    return False
        return True

if __name__ == "__main__":
    instance = Solution()
    print(instance.validParentheses("[{}]"))
