# Generated By lexicon-dsa CLI tool.
# Author: Saptak Sengupta(deeps.sengupta@gmail.com)
# Github: https://github.com/saptaksengupta/

class MotuAndPatlu:

    def getWinner(self, icecreams, length):
        winner = 'Patlu'
        indexOfPatlu = length - 1
        indexOfMotu = 0

        motuTotalTime = patluTotalTime = 0

        while indexOfPatlu >= indexOfMotu:
            
            if motuTotalTime < patluTotalTime * 2:
                motuTotalTime += icecreams[indexOfMotu]
                indexOfMotu += 1
            else:
                patluTotalTime += icecreams[indexOfPatlu]
                indexOfPatlu -= 1
            
        
        patluEaten = length - 1 - indexOfPatlu
        motuEaten = indexOfMotu
        
        if motuEaten > patluEaten:
            winner = 'Motu'
        
        print(motuEaten, patluEaten)
        print(winner)


if __name__ == "__main__":
    instance = MotuAndPatlu() 
    numberOfTest = int(input('Number Of test: '))
    inputList = []
    for i in range(0, numberOfTest):
        icecreams = input('Enter ice creams: ').split()
        icecreams = [int(x) for x in icecreams]
        inputList.append(icecreams)
    

    for i in range(0, len(inputList)):
        instance.getWinner(inputList[i], len(inputList[i]))