# Generated By lexicon-dsa CLI tool.
# Author: Saptak Sengupta(deeps.sengupta@gmail.com)
# Github: https://github.com/saptaksengupta/

class Solution:

    # Complete the demoFunction function below.
    # You should change the name accordinglly.
    def getSequence(self, arr):

        s = set()
        res = 0
        for i in range(len(arr)):
            s.add(arr[i])

        for i in range(len(arr)):

            if arr[i] - 1 not in s:

                j = arr[i]
                while j in s:
                    j += 1
                
                res = max(res, j - arr[i])
        
        return res


if __name__ == "__main__":
    testArr = [100, 4, 200, 1, 2, 3]
    instance = Solution()
    print(instance.getSequence(testArr))
