# Generated By lexicon-dsa CLI tool.
# Author: Saptak Sengupta(deeps.sengupta@gmail.com)
# Github: https://github.com/saptaksengupta/

class Solution:
    
    # Complete the demoFunction function below.
    # You should change the name accordinglly.
    def getMaxSubArraySum(self, arr):
        maxSumsofar = arr[0]
        maxSumEnd= arr[0]

        for i in range(1, len(arr)):
            maxSumsofar = maxSumsofar + arr[i]

            if maxSumsofar > maxSumEnd:
                maxSumEnd = maxSumsofar

            if maxSumsofar < 0:
                maxSumsofar = 0

        return maxSumEnd 


if __name__ == "__main__":

    demoArr = [-2,1,-3,4,-1,2,1,-5,4]
    # demoArr = [-2]
    instance = Solution()
    maxSum = instance.getMaxSubArraySum(demoArr)

    print(maxSum)