# Generated By lexicon-dsa CLI tool.
# Author: Saptak Sengupta(deeps.sengupta@gmail.com)
# Github: https://github.com/saptaksengupta/

class Solution:

    def __init__(self):
        self.bucket = {}

    def groupAnagrams(self, inputArr):
        for x in range(0, len(inputArr)):
            sortedWord = "".join(sorted(inputArr[x]))
            if sortedWord not in self.bucket:
                self.bucket[sortedWord] = [inputArr[x]]
            else:
                self.bucket[sortedWord].append(inputArr[x])

        return self.renderOutput(self.bucket)

    def renderOutput(self, bucket):
        result = []
        for i in bucket:
            result.append(bucket[i])
        return result

if __name__ == "__main__":
    arr = ["cab","tin","pew","duh","may","ill","buy","bar","max","doc"]
    instance = Solution()
    bucket = instance.groupAnagrams(arr)
    print(bucket)
