# Generated By lexicon-dsa CLI tool.
# Author: Saptak Sengupta(deeps.sengupta@gmail.com)
# Github: https://github.com/saptaksengupta/

class threeSum:
    def __init__(self):
        self.target = 0
        self.triplets = []

    # Complete the demoFunction function below.
    # You should change the name accordinglly.
    def getTriplets(self, arr):
        arr.sort()
        length = len(arr)

        for i in range(length - 2):
            left = i + 1
            right = length - 1

            if i > 0 and arr[i] == arr[i-1]:
                continue

            while left < right:
                currentSum = arr[i] + arr[left] + arr[right]
                if currentSum < self.target:
                    left += 1
                elif currentSum > self.target:
                    right -= 1
                else:
                    self.triplets.append([ arr[i], arr[left], arr[right] ])
                    while left < right and arr[left] == arr[left + 1]:
                        left += 1
                        
                    while left < right and arr[right] == arr[right - 1]:
                        right -= 1
                    left += 1
                    right -= 1

        return self.triplets


if __name__ == "__main__":

    myArr = input('Enter array: ').split()
    myArr = [int(x) for x in myArr]

    instance = threeSum()
    triplets = instance.getTriplets(myArr)

    print(triplets)
