'use strict';
// Generated By lexicon-dsa CLI tool.
// Author: Saptak Sengupta(deeps.sengupta@gmail.com)
// Github: https://github.com/saptaksengupta/

// Diameter of binary tree can be calculated as
// -- Longest path between two nodes
// -- Path does not need to pass via root.

function Tree(value) {
    this.value = value;
    this.left = null;
    this.right = null;
}

function getDiameter(root) {
    var max = [];
    max[0] = 0;
    getMaxHightOfTree(root, max);
    return max[0];
}

function getMaxHightOfTree(root, maxi) {
    if (root == null) {
        return 0;
    }

    var left = getMaxHightOfTree(root.left, maxi);
    var right = getMaxHightOfTree(root.right, maxi);

    maxi[0] = Math.max(maxi[0], left + right);
    
    return 1 + Math.max(left, right);
}



function main() {
    var tree = new Tree(1);
    tree.left = new Tree(2);
    tree.right = new Tree(3);
    tree.right.left = new Tree(4);
    tree.right.left.left = new Tree(5);
    tree.right.left.left.left = new Tree(5);
    console.log(getDiameter(tree));
}

main();

