'use strict';
// Generated By lexicon-dsa CLI tool.
// Author: Saptak Sengupta(deeps.sengupta@gmail.com)
// Github: https://github.com/saptaksengupta/


// Complete the demoFunction function below.
// You should change the name accordinglly.
function Tree(value) {
    this.value = value;
    this.left = null;
    this.right = null;
}

function iterativePreOrderTraversal(root) {
    var stack = new Array();

    stack.push(root);

    while(stack.length > 0) {
        var currentNode = stack.pop();

        if (currentNode.value) {
            console.log(currentNode.value);
        }
    
        if (currentNode.right) {
            stack.push(currentNode.right);
        }
        if (currentNode.left) {
            stack.push(currentNode.left);
        }
    }
}

function main() {
    var tree = new Tree(1);
    tree.left = new Tree(2);
    tree.right = new Tree(7);
    tree.left.left = new Tree(3);
    tree.left.right = new Tree(4);
    tree.left.right.left = new Tree(5);
    tree.left.right.right = new Tree(6);
    console.log(iterativePreOrderTraversal(tree));
}

main();

