'use strict';
// Generated By lexicon-dsa CLI tool.
// Author: Saptak Sengupta(deeps.sengupta@gmail.com)
// Github: https://github.com/saptaksengupta/

function Tree(value) {
    this.value = value;
    this.left = null;
    this.right = null;
}

function zigzagMove(root) {
    const q = [];
    const res = [];
    let ltr = true;

    q.push(root);
    while (q.length > 0) {
        const len = q.length;
        const localList = [];
        for (let i = 0; i < len; i++) {
            const it = q.shift();
            const index = ltr ? i : len - 1 - i;
            localList[index] = it.value;

            if (it.left) {
                q.push(it.left);
            }

            if (it.right) {
                q.push(it.right);
            }
        }
        res.push(localList);
        ltr = !ltr;
    }
    return res;
}



function main() {
    var tree = new Tree(1);
    tree.left = new Tree(2);
    tree.right = new Tree(3);
    tree.left.left = new Tree(4);
    tree.left.right = new Tree(5);
    tree.right.right= new Tree(6);
    console.log(zigzagMove(tree));
}

main();

