# Generated By lexicon-dsa CLI tool.
# Author: Saptak Sengupta(deeps.sengupta@gmail.com)
# Github: https://github.com/saptaksengupta/

INT_MAX = 4294967296
INT_MIN = -4294967296

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right


class Solution:
    def isValidBST(self, root: TreeNode) -> bool:
        return self.isValidBstUtil(root, INT_MAX, INT_MIN)
    
    def isValidBstUtil(self, node: TreeNode, maxi, mini):
        if node is None:
            return True
        
        if node.val > maxi or node.val < mini:
            return False

        return (self.isValidBstUtil(node.left, node.val - 1, mini) 
            and self.isValidBstUtil(node.right, maxi, node.val + 1))

if __name__ == "__main__":

    root = TreeNode(4) 
    root.left = TreeNode(2) 
    root.right = TreeNode(5) 
    root.left.left = TreeNode(1) 
    root.left.right = TreeNode(3) 

    instance = Solution()
    print(instance.isValidBST(root))
