# Generated By lexicon-dsa CLI tool.
# Author: Saptak Sengupta(deeps.sengupta@gmail.com)
# Github: https://github.com/saptaksengupta/

#      3
#    / \
#   9  20
#     /  \
#    15   7

class TreeNode:

    def __init__(self, data):
        self.data = data
        self.left = None
        self.right = None

class Solution:
    
    def maxDepth(self, root: TreeNode):
        
        if root is None:
            return 0
        
        lDepth = self.maxDepth(root.left) + 1
        rDepth = self.maxDepth(root.right) + 1

        return max(lDepth, rDepth)

if __name__ == "__main__":

    root = TreeNode(3)

    root.left = TreeNode(9)
    root.right = TreeNode(20)
    root.right.left = TreeNode(15)
    root.right.right = TreeNode(7) 

    instance = Solution()
    maxDepth = instance.maxDepth(root)
    print(maxDepth)
