# Generated By lexicon-dsa CLI tool.
# Author: Saptak Sengupta(deeps.sengupta@gmail.com)
# Github: https://github.com/saptaksengupta/

class demoClass:
    # Complete the demoFunction function below.
    # You should change the name accordinglly.
    def countApplesAndOranges(self, s, t, a, b, apples, oranges):

        appleCount = 0
        orangeCount = 0

        for x in range(len(apples)):
            loc = a + apples[x]
            if loc >= s and loc <= t:
                appleCount += 1

        
        for y in range(len(oranges)):
            loc = b + oranges[y]
            if loc >= s and loc <= t:
                orangeCount += 1
        
        print(appleCount)
        print(orangeCount)

if __name__ == "__main__":
    instance = demoClass()
    s = 7
    t = 11 
    a = 5
    b = 15
    apples = [-2, 2, 1]
    oranges = [5, -6]
    print(oranges)
    instance.countApplesAndOranges(s, t, a, b, apples, oranges)
