# Generated By lexicon-dsa CLI tool.
# Author: Saptak Sengupta(deeps.sengupta@gmail.com)
# Github: https://github.com/saptaksengupta/

class demoClass:

    def __init__(self):
        self.grades = []

    def getNextMulOfFive(self, number):
        reminder = number % 5
        return number + (5 - reminder)

    # Complete the demoFunction function below.
    # You should change the name accordinglly.
    def gradingStudents(self, arr):

        for i in range(len(arr)):

            if arr[i] < 38:
                self.grades.append(arr[i])
                continue
            
            nextMultiple = self.getNextMulOfFive(arr[i])
            if nextMultiple - arr[i] < 3:
                self.grades.append(nextMultiple)
            else:
                self.grades.append(arr[i])    
        
        return self.grades


if __name__ == "__main__":
    myArr = input('Enter array: ').split()
    myArr = [int(x) for x in myArr]
    instance = demoClass()
    finalGrades = instance.gradingStudents(myArr)
    print(finalGrades)
