# Generated By lexicon-dsa CLI tool.
# Author: Saptak Sengupta(deeps.sengupta@gmail.com)
# Github: https://github.com/saptaksengupta/

class demoClass:
    def __init__(self):
        self.isPossible = False

    # Complete the demoFunction function below.
    # You should change the name accordinglly.
    def checkIfPossible(self, x1, v1, x2, v2):

        if v2 > v1:
            return "NO"
        else: 
            if v1 != v2 and ((x2 - x1) % (v2 - v1) == 0):
                return "YES"
            else: 
                return "NO"
        

if __name__ == "__main__":
    instance = demoClass()
    res = instance.checkIfPossible(0, 3, 4, 2)

    print(res)
