# Generated By lexicon-dsa CLI tool.
# Author: Saptak Sengupta(deeps.sengupta@gmail.com)
# Github: https://github.com/saptaksengupta/

from collections import defaultdict


class Graph:
    def __init__(self):
        self.graph = {
            'A': ['B', 'C'],
            'B': ['D', 'E'],
            'C': ['F'],
            'D': [],
            'E': ['F'],
            'F': []
        }
        self.visited = []
        self.queue = []


    def BFS(self, s):
        self.visited.append(s)
        self.queue.append(s)
        
        while self.queue:
            s = self.queue.pop(0)
            print(s, end=' ')

            for neighbour in self.graph[s]:
                if neighbour not in self.visited:
                    self.visited.append(neighbour)
                    self.queue.append(neighbour)


if __name__ == "__main__":
    
    g = Graph()
    g.BFS('A')