# Generated By lexicon-dsa CLI tool.
# Author: Saptak Sengupta(deeps.sengupta@gmail.com)
# Github: https://github.com/saptaksengupta/

class Graph :
    def __init__(self):
        self.graph = {
            'A': ['B', 'C'],
            'B': ['D', 'E'],
            'C': ['F'],
            'D': [],
            'E': ['F'],
            'F': []
        }

        self.visited = set()
        
    # Complete the demoFunction function below.
    # You should change the name accordinglly.
    def DFS(self, node):
        
        if node not in self.visited:
            print(node, end=" ")
            self.visited.add(node)
            for neighbour in self.graph[node]:
                self.DFS(neighbour)


if __name__ == "__main__":
    instance = Graph()
    instance.DFS('A')
